networks:
  default:
    name: test
    driver: bridge

services:
  service1:
    build: ./service_1
    expose:
      - "8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 5s
      retries: 3

  service2:
    build: ./service_2
    expose:
      - "8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 5s
      retries: 3

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      service1:
        condition: service_healthy
      service2:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      
    
  